eqfeed_callback({
"type": "FeatureCollection",
"name": "test",
"crs": { "type": "name", "properties": { "name": "urn:ogc:def:crs:OGC:1.3:CRS84" } },
"features": [
{ "type": "Feature", "properties": { "Name": "Site developer: Nordkraft DC Sites ", "description": "https:\/\/nordkraftdc.no ", "timestamp": null, "begin": null, "end": null, "altitudeMode": null, "tessellate": -1, "extrude": 0, "visibility": -1, "drawOrder": null, "icon": null }, "geometry": { "type": "Point", "coordinates": [ 17.3289483, 68.3877679, 0.0 ] } },
{ "type": "Feature", "properties": { "Name": "Site developer: Arctic host", "description": "https:\/\/arctichost.cloud", "timestamp": null, "begin": null, "end": null, "altitudeMode": null, "tessellate": -1, "extrude": 0, "visibility": -1, "drawOrder": null, "icon": null }, "geometry": { "type": "Point", "coordinates": [ 14.7995913, 67.0298743, 0.0 ] } },
{ "type": "Feature", "properties": { "Name": "Site developer: GreenByte", "description": "https:\/\/www.greenbyte.no ", "timestamp": null, "begin": null, "end": null, "altitudeMode": null, "tessellate": -1, "extrude": 0, "visibility": -1, "drawOrder": null, "icon": null }, "geometry": { "type": "Point", "coordinates": [ 5.0146064, 61.0418394, 0.0 ] } },
{ "type": "Feature", "properties": { "Name": "Site developer: Nordavind DC Sites", "description": "https:\/\/nordavind.com", "timestamp": null, "begin": null, "end": null, "altitudeMode": null, "tessellate": -1, "extrude": 0, "visibility": -1, "drawOrder": null, "icon": null }, "geometry": { "type": "Point", "coordinates": [ 10.8153877, 60.9352756, 0.0 ] } },
{ "type": "Feature", "properties": { "Name": "Site developer: New Kaupang", "description": "https:\/\/newkaupang.com", "timestamp": null, "begin": null, "end": null, "altitudeMode": null, "tessellate": -1, "extrude": 0, "visibility": -1, "drawOrder": null, "icon": null }, "geometry": { "type": "Point", "coordinates": [ 5.2782783, 59.4277984, 0.0 ] } },
{ "type": "Feature", "properties": { "Name": "Site developer: Oslo Data Center Location", "description": "https:\/\/oslodclo.com ", "timestamp": null, "begin": null, "end": null, "altitudeMode": null, "tessellate": -1, "extrude": 0, "visibility": -1, "drawOrder": null, "icon": null }, "geometry": { "type": "Point", "coordinates": [ 10.1678989, 60.1148812, 0.0 ] } },
{ "type": "Feature", "properties": { "Name": "Site developer: Statkraft DC Sites", "description": "https:\/\/statkraftdatacentersites.com", "timestamp": null, "begin": null, "end": null, "altitudeMode": null, "tessellate": -1, "extrude": 0, "visibility": -1, "drawOrder": null, "icon": null }, "geometry": { "type": "Point", "coordinates": [ 9.8163364, 59.3059144, 0.0 ] } },
{ "type": "Feature", "properties": { "Name": "Site developer: Bulk Infrastructure", "description": "https:\/\/bulk.no\/data-centers", "timestamp": null, "begin": null, "end": null, "altitudeMode": null, "tessellate": -1, "extrude": 0, "visibility": -1, "drawOrder": null, "icon": null }, "geometry": { "type": "Point", "coordinates": [ 7.5970981, 58.3506411, 0.0 ] } },
{ "type": "Feature", "properties": { "Name": "Site developer: Data Center in Troms", "description": "https:\/\/www.dcit.no\/", "timestamp": null, "begin": null, "end": null, "altitudeMode": null, "tessellate": -1, "extrude": 0, "visibility": -1, "drawOrder": null, "icon": null }, "geometry": { "type": "Point", "coordinates": [ 19.2326061, 69.6159242, 0.0 ] } }
]
});
